### PR TITLE
update to Riak 2.1.1

### PR DESCRIPTION
**Pull request by holidayworking**
I have updated the version of Riak to 2.1.1.

Please confirm.

### CODE REVIEW

**Comment by mbbroberg** [comment]
Hey @glickbot, could you weigh in here? And thank you @holidayworking!

**Comment by holidayworking** [comment]
@mjbrender thank you.

@glickbot I was wondering if you had chance to look at this pull request. Please let me know if you have any questions or concerns.

**Comment by holidayworking** [comment]
@glickbot @macintux I want to tell me this pull request is OK or NG.

**Comment by mbbroberg** [comment]
Hey @holidayworking I gave @glickbot another ping. Thanks for your patience!

**Pull request merged**
